### ISSUE TITLE
Error in interactive mode

### ISSUE THREAD

**Issue by Reggyyy** [cmusphinx/g2p-seq2seq#123] opened 2018-05-10 17:57 UTC
I followed the tutorial and this happened:

(TrainingPy2) rgb@rgb-HP-Notebook:~/Desktop/TrainingPy2/g2pTools$ g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict/
Traceback (most recent call last):
  File "/home/rgb/Desktop/TrainingPy2/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.1.4a0', 'console_scripts', 'g2p-seq2seq')()
  File "/home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/app.py", line 111, in main
    params.hparams = g2p_trainer_utils.load_params(FLAGS.model_dir)
  File "/home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/g2p_trainer_utils.py", line 210, in load_params
    model_params = json.load(open(params_file_path))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by nshmyrev** [comment] 2018-05-11 12:34
Duplicate of issue #115

**Closed by nshmyrev** 2018-05-11 12:34 UTC
