### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by faizann24** [cmusphinx/g2p-seq2seq#42] opened 2016-07-14 20:42 UTC
I am trying to do everything right but this error still persists.

Creating 2 layers of 64 units.
Created model with fresh parameters.
global step 200 learning rate 0.5000 step-time 3.09 perplexity 1.57
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 67, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 217, in train
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 253, in __run_evals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 250, in get_batch
    encoder_input, decoder_input = random.choice(data[bucket_id])
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range

**Comment by nshmyrev** [comment] 2016-07-14 20:45
Duplicate of https://github.com/cmusphinx/g2p-seq2seq/issues/38

**Comment by faizann24** [comment] 2016-07-14 20:45
My dictionary file:
بِسْمِ B I S M I
ٱللَّهِ A L AH I
ٱلرَّحْمَـٰنِ R AH M AN
ٱلرَّحِيمِ A R AH I M

My phonemes:
SIL fricative
OU vowel
A vowel
B fricative
:AAA fricative
Y fricative
I vowel
M fricative
S fricative
L fricative
AH fricative
R fricative
AN fricative

**Closed by nshmyrev** 2016-07-14 20:45 UTC
