### ISSUE TITLE
N-best prononciations? 

### ISSUE THREAD

**Issue by aghasemi** [cmusphinx/g2p-seq2seq#80] opened 2017-04-23 09:42 UTC
Hi,
Is there the possibility to retrieve multiple (N-best) pronunciations for a given word instead of one?

Many thanks

**Comment by nshmyrev** [comment] 2017-04-23 10:06
Not possible yet, duplicate of https://github.com/cmusphinx/g2p-seq2seq/issues/45

**Closed by nshmyrev** 2017-04-23 10:06 UTC
