### ISSUE TITLE
Error in starting the interactive session

### ISSUE THREAD

**Issue by mausamjain** [cmusphinx/g2p-seq2seq#107] opened 2018-04-09 06:26 UTC
`$ g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict`

`from ._conv import register_converters as _register_converters`
`Traceback (most recent call last):`
`  File "~/anaconda2/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.0.0a0', 'console_scripts', 'g2p-seq2seq')()`
`  File "~/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)`
`  File "~/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point`
    return ep.load()
`  File "~/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()`
`  File "~/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)`
`  File "~/anaconda2/lib/python2.7/site-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app`
`  File "~/anaconda2/lib/python2.7/site-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/app.py", line 31, in <module>
    from g2p_seq2seq.g2p import G2PModel`
`  File "~/anaconda2/lib/python2.7/site-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/g2p.py", line 30, in <module>
    from g2p_seq2seq import g2p_trainer_utils`
`  File "~/anaconda2/lib/python2.7/site-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/g2p_trainer_utils.py", line 26, in <module>
    from tensor2tensor.utils import input_fn_builder`
`ImportError: cannot import name input_fn_builder`

I have tensorflow version 1.4.1 and tensor2tensor version 1.5.5 installed.

**Comment by nurtas-m** [comment] 2018-04-09 11:17
Thank you for the report! This bug appears with tensor2tensor versions higher than 1.3.2. We will try to fix it in next release.

**Comment by michem32** [comment] 2018-04-16 11:33
Class 'g2p_trainer_utils.py' tries to import the following classes from 'tensor2tensor.utils':   
- model_builder.py
- input_fn_builder.py
- trainer_utils.py
Unfortunatelly they are not available anymore in the utils folder:
https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/utils

I managed to find them in a previous version, for example here:
https://github.com/tensorflow/tensor2tensor/tree/9a651716367308fe55820dc37578371e177e5d91/tensor2tensor/utils

But, I don't know how stable they are.

Any update on that?

**Comment by nurtas-m** [comment] 2018-04-18 14:33
Yes, there are a lot of changes in tensor2tensor starting from version 1.4.0. Now I am trying to modify our code in order to g2p_seq2seq work with the new tensor2tensor.

**Comment by nshmyrev** [comment] 2018-05-11 12:47
@nurtas-m is this fixed already?

**Comment by nurtas-m** [comment] 2018-05-11 12:53
Fixed partially. We need to upload new pre-trained models.

**Comment by nurtas-m** [comment] 2018-05-11 15:41
Fixed with commit 762de8f57eb74bccaa3a9239f4782ab4de44af84

**Closed by nurtas-m** 2018-05-11 15:41 UTC

**Comment by AshishDagar** [comment] 2018-06-06 12:32
I am trying to run _**g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict**_ command but getting below error. Installed g2p-seq2seq from pip command. Can anyone help, I am not sure what to do next.

Traceback (most recent call last):
  File "/root/miniconda2/bin/g2p-seq2seq", line 7, in <module>
    from g2p_seq2seq.app import main
  File "/root/miniconda2/lib/python2.7/site-packages/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "/root/miniconda2/lib/python2.7/site-packages/g2p_seq2seq/app.py", line 31, in <module>
    from g2p_seq2seq.g2p import G2PModel
  File "/root/miniconda2/lib/python2.7/site-packages/g2p_seq2seq/g2p.py", line 28, in <module>
    from g2p_seq2seq import g2p_trainer_utils
  File "/root/miniconda2/lib/python2.7/site-packages/g2p_seq2seq/g2p_trainer_utils.py", line 26, in <module>
    from tensor2tensor.utils import input_fn_builder
ImportError: cannot import name input_fn_builder

**Comment by nurtas-m** [comment] 2018-06-06 14:35
Hello, @AshishDagar 
Install g2p-seq2seq from github, please. Also, current version of g2p-seq2seq toolkit requires tensor2tensor ver=1.5.7.

**Comment by AshishDagar** [comment] 2018-06-11 10:33
Hello, @nurtas-m 

I tried what you said. But getting below error while running test using **python3 setup.py test** command

running test
running egg_info
writing dependency_links to g2p_seq2seq.egg-info/dependency_links.txt
writing entry points to g2p_seq2seq.egg-info/entry_points.txt
writing top-level names to g2p_seq2seq.egg-info/top_level.txt
writing requirements to g2p_seq2seq.egg-info/requires.txt
writing g2p_seq2seq.egg-info/PKG-INFO
reading manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
running build_ext
test_decode (tests.g2p_unittest.TestG2P) ... /home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py:210: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ashishdagar/g2p-seq2seq/tests/models/decode/model.params' mode='r' encoding='UTF-8'>
  model_params = json.load(open(params_file_path))
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/trainer_lib.py:148: RunConfig.__init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/tf_logging.py:121: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  _get_logger().warn(msg, *args, **kwargs)
WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f83323c19d8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:279: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
WARNING:tensorflow:From /home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py:157: Experiment.__init__ (from tensorflow.contrib.learn.python.learn.experiment) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.estimator.train_and_evaluate. You will also have to convert to a tf.estimator.Estimator.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f8332369ae8>) includes params argument, but params are not passed to Estimator.
ERROR
test_evaluate (tests.g2p_unittest.TestG2P) ... WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f83323c1ae8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f8332369ae8>) includes params argument, but params are not passed to Estimator.
ERROR
test_train (tests.g2p_unittest.TestG2P) ... WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f8332369ae8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f8332369bf8>) includes params argument, but params are not passed to Estimator.
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:55: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
WARNING:tensorflow:Without a Problem, T2TModel.bottom is a passthrough.
ERROR

======================================================================
ERROR: test_decode (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ashishdagar/g2p-seq2seq/tests/g2p_unittest.py", line 35, in test_decode
    g2p_model.decode(output_file_path=output_file_path)
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 289, in decode
    inputs, decodes = self.__decode_from_file(self.test_path)
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 424, in __decode_from_file
    problem_id = self.decode_hp.problem_idx
AttributeError: 'HParams' object has no attribute 'problem_idx'

======================================================================
ERROR: test_evaluate (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ashishdagar/g2p-seq2seq/tests/g2p_unittest.py", line 48, in test_evaluate
    g2p_model.evaluate()
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 325, in evaluate
    correct, errors = self.calc_errors(self.test_path)
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 479, in calc_errors
    inputs, decodes = self.__decode_from_file(decode_file_path)
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 424, in __decode_from_file
    problem_id = self.decode_hp.problem_idx
AttributeError: 'HParams' object has no attribute 'problem_idx'

======================================================================
ERROR: test_train (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 432, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 343, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 0.0 of type 'float' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashishdagar/g2p-seq2seq/tests/g2p_unittest.py", line 25, in test_train
    g2p_model.train()
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 255, in train
    execute_schedule(self.exp, self.params)
  File "/home/ashishdagar/g2p-seq2seq/g2p_seq2seq/g2p.py", line 587, in execute_schedule
    getattr(exp, params.schedule)()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 666, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 389, in train
    saving_listeners=self._saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 876, in _call_train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/t2t_model.py", line 923, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/t2t_model.py", line 973, in estimator_model_fn
    logits, losses_dict = model(features)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/t2t_model.py", line 153, in call
    sharded_logits, losses = self.model_fn_sharded(sharded_features)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/t2t_model.py", line 208, in model_fn_sharded
    sharded_logits, sharded_losses = dp(self.model_fn, datashard_to_features)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/expert_utils.py", line 231, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/t2t_model.py", line 242, in model_fn
    body_out = self.body(transformed_features)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/models/transformer.py", line 161, in body
    inputs, target_space, hparams, features=features, losses=losses)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/models/transformer.py", line 75, in encode
    inputs, target_space, hparams, features=features))
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/models/transformer.py", line 664, in transformer_prepare_encoder
    encoder_padding = common_attention.embedding_to_padding(encoder_input)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/utils/expert_utils.py", line 58, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor-1.6.3-py3.5.egg/tensor2tensor/layers/common_attention.py", line 776, in embedding_to_padding
    return tf.to_float(tf.equal(emb_sum, 0.0))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2529, in equal
    "Equal", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 519, in _apply_op_helper
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'y' of op 'Equal', got 0.0 of type 'float' instead.

----------------------------------------------------------------------
Ran 3 tests in 0.226s

FAILED (errors=3)

**Comment by nurtas-m** [comment] 2018-06-13 08:54
Ok, as I understand from the logs, you had launched: 
- unittests with python3.5
- and interactive mode with python2.7

The problem is that you had installed another version of tensor2tensor (not 1.5.7) for python2.7

**Comment by AshishDagar** [comment] 2018-06-18 06:49
@nurtas-m 

Now working fine after installing tensor2tensor version 1.5.7. Thanks..!!!!

**Comment by temitopefunmi** [comment] 2019-09-05 07:59
I tried to run g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict but i get the error:
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\my-env\Scripts\g2p-seq2seq-script.py", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq\__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq\app.py", line 31, in <module>
    from g2p_seq2seq.g2p import G2PModel
  File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq\g2p.py", line 30, in <module>
    from tensor2tensor.utils import trainer_utils
ImportError: cannot import name 'trainer_utils'

Please what do i do?
